/// Flutter icons ResourceInfoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ResourceInfoIcons
///      fonts:
///       - asset: fonts/ResourceInfoIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class ResourceInfoIcons {
  ResourceInfoIcons._();

  static const _kFontFam = 'ResourceInfoIcons';
  static const String? _kFontPkg = null;

  static const IconData bound = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burnt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData min = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData max = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
