/// Flutter icons ZeldaStaminaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZeldaStaminaIcons
///      fonts:
///       - asset: fonts/ZeldaStaminaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ZeldaStaminaIcons {
  ZeldaStaminaIcons._();

  static const _kFontFam = 'ZeldaStaminaIcons';
  static const String? _kFontPkg = null;

  static const IconData container =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hFull =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h50 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h75 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h25 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const List<IconData> allIcons = <IconData>[
    container,
    hFull,
    h75,
    h50,
    h25,
  ];
}
